# Uncomment the next line to define a global platform for your project

#source 'https://cdn.cocoapods.org'

platform :ios, '14.0'

target 'iOSTimeGPS' do
  
  source 'https://github.com/CocoaPods/Specs.git'

  
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  inhibit_all_warnings!
  
  pod 'GPCam', :path => 'gps_pods/GP66BU_P' , :subspecs => ['BBD59MM', 'OpenCV']

  pod 'SnapKit', '~> 5.7.0'
  pod 'Alamofire', '5.6.4'
  pod 'Kingfisher', '6.3.1'
  pod 'DeviceKit', '~> 5.2'
  # firebase
  pod 'FirebaseAnalytics', '10.24.0'
  # location
  pod 'SwiftLocation/Core'
  pod 'KeychainAccess', '4.2.2'
  pod 'QCloudCOSXML/Transfer'
  pod 'CryptoSwift', '~> 1.8.3'
  #DateToolsSwift
  pod 'DateToolsSwift'
  pod "Solar-dev", "~> 3.0"
  pod 'CocoaLumberjack/Swift', '3.7.4'
  pod 'Zip', '~> 2.1'

end

post_install do|installer|
   #解决问题一
   find_and_replace("Pods/FBRetainCycleDetector/FBRetainCycleDetector/Layout/Classes/FBClassStrongLayout.mm",
       "layoutCache[currentClass] = ivars;", "layoutCache[(id)currentClass] = ivars;")
   #解决问题二
   find_and_replace("Pods/FBRetainCycleDetector/fishhook/fishhook.c",
   "indirect_symbol_bindings[i] = cur->rebindings[j].replacement;", "if (i < (sizeof(indirect_symbol_bindings) /
        sizeof(indirect_symbol_bindings[0]))) { \n indirect_symbol_bindings[i]=cur->rebindings[j].replacement; \n }")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
    FileUtils.chmod("+w",name) #add
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
         puts "Fix: " + name
         File.open(name, "w") { |file| file.puts replace }
         STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
